site: DACC
url: daccpampa.github.io
title: DACC
description: Diretório Acadêmico do curso de Bacharelado em Ciência da Computação da Universidade Federal do Pampa
twitter:
  username: #yourusername
  card: summary
  creator: #yourusername
author:
  name: DACC
  avatar:
  email: dacc@unipampa.edu.br
  url: #yoururl
permalink: pretty

baseurl: ""

highlighter: none

exclude: [.jekyll-cache, vendor]

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  docs:
    output: true
    permalink: /docs/:slug
  posts:
    output: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "docs"
    values:
      layout: "doc"
