site: DACC
url: https://daccpampa.org/
locale: pt-BR
title: DACC
description: Diretório Acadêmico do curso de Bacharelado em Ciência da Computação da Universidade Federal do Pampa
twitter:
  username: #yourusername
  card: summary
  creator: #yourusername
author:
  name: DACC
  avatar:
  email: diretores@daccpampa.org
  url: #yoururl

exclude: [.jekyll-cache, vendor, Gem*, README*, LICENSE, CNAME]

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  docs:
    output: true
    permalink: /docs/:name
  posts:
    output: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "pages"
    values:
      priority: 0
  -
    scope:
      path: ""
      type: "docs"
    values:
      layout: "doc"
